### ISSUE TITLE
kill: did not work 

### ISSUE THREAD

**Issue by mh-cbon** [loov/watchrun#4]
please see,

```sh
+ cd /home/ubuntu/go/src/github.com/otiai10/ocrserver
+ /home/ubuntu/go/bin/watchrun go run main.go
<< 2017-08-08 11:58:01.104253773 +0000 UTC >>
<<  run: go run main.go >>
[ocrserver] listening on port :8080
<< kill: go run main.go >>
<< 2017-08-08 11:58:13.191581402 +0000 UTC >>
<<  run: go run main.go >>
[ocrserver] listening on port :8080
[ocrserver] listen tcp :8080: bind: address already in use
<< done: go run main.go 1.695240984s >>
<< kill: go run main.go >>
<< 2017-08-08 11:58:16.373473222 +0000 UTC >>
<<  run: go run main.go >>
[ocrserver] listening on port :8080
[ocrserver] listen tcp :8080: bind: address already in use
<< done: go run main.go 1.596964503s >>
<< kill: go run main.go >>
<< 2017-08-08 11:58:45.491686577 +0000 UTC >>
<<  run: go run main.go >>
[ocrserver] listening on port :8080
[ocrserver] listen tcp :8080: bind: address already in use
<< done: go run main.go 2.039562825s >>
<< kill: go run main.go >>
<< 2017-08-08 12:01:03.79136513 +0000 UTC >>
<<  run: go run main.go >>
[ocrserver] listening on port :8080
[ocrserver] listen tcp :8080: bind: address already in use
<< done: go run main.go 1.661087543s >>
```

kill fails, restart fails, app not updated. 

```
vagrant ssh -c "go version"
go version go1.8.3 linux/amd64

vagrant ssh -c "lsb_release -a"
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by egonelbre** [comment]
The reason kill is not working is because it only kills immediate children, `go run` itself creates multiple child processes that aren't caught and killed.

This can be overcome by using:
```
watchrun go build -i . == ocrserver
```

This will ensure that `watchrun` is starting the process, not `go run`.

**Comment by egonelbre** [comment]
_PS: if you know a way to kill the whole process tree, then that would be nice_

**Comment by mh-cbon** [comment]
thanks!

> The reason kill is not working is because it only kills immediate children, go run itself creates multiple child processes that aren't caught and killed.

yeah looks likes this, I was buggy i could not find a bug report about that.

> watchrun go build -i . == ocrserver

For completeness, my command is like `~/go/bin/watchrun -verbose go build -i . == ./ocrserver`, just because my path are *****, should not be a worry.

now, see:

```sh
+ /home/ubuntu/go/bin/watchrun -verbose go build -i . == ./ocrserver
Options:
    interval   :  300ms
    recursive  :  true
    monitoring :  [.]
    ignoring   :  [.* ~* *~ *.[ao] *.so *.obj *.log *.test *.prof *.exe *.dll]
    caring     :  []

Processes:
    go build -i .
    ./ocrserver 

<< 2017-08-08 12:57:32.140529238 +0000 UTC >>
<<  run: go build -i . >>
<< done: go build -i . 1.188853599s >>
<<  run: ./ocrserver  >>
[ocrserver] listening on port :8080
<< kill: ./ocrserver  >>
2017/08/08 12:57:33 proc kill <nil>
<< 2017-08-08 12:57:33.846015768 +0000 UTC >>
<<  run: go build -i . >>
<< done: go build -i . 1.088555013s >>
<<  run: ./ocrserver  >>
[ocrserver] listening on port :8080
^C<< kill: ./ocrserver  >>
2017/08/08 12:57:35 proc kill <nil>
<< 2017-08-08 12:57:35.578894569 +0000 UTC >>
```
: (

Meanwhile, i worked around with

reload.sh
```sh

set -x
set -e

killall main -9 || echo ok
go run main.go
```

And `~/go/bin/watchrun -verbose sh reload.sh`

```sh
+ /home/ubuntu/go/bin/watchrun -verbose sh reload.sh
Options:
    interval   :  300ms
    recursive  :  true
    monitoring :  [.]
    ignoring   :  [.* ~* *~ *.[ao] *.so *.obj *.log *.test *.prof *.exe *.dll]
    caring     :  []

Processes:
    sh reload.sh

<< 2017-08-08 13:01:55.808928066 +0000 UTC >>
<<  run: sh reload.sh >>
+ set -e
+ killall main -9
main: no process found
+ echo ok
ok
+ go run main.go
[ocrserver] listening on port :8080
<< kill: sh reload.sh >>
<< 2017-08-08 13:02:07.702002883 +0000 UTC >>
<<  run: sh reload.sh >>
+ set -e
+ killall main -9
+ go run main.go
[ocrserver] listening on port :8080
<< kill: sh reload.sh >>
<< 2017-08-08 13:02:11.105639328 +0000 UTC >>
<<  run: sh reload.sh >>
+ set -e
+ killall main -9
+ go run main.go
[ocrserver] listening on port :8080
```

all good!

I must notice that, **hopefully i don t work on windows**, i m not sure they have a kill command, this is unclear.

> PS: if you know a way to kill the whole process tree, then that would be nice

I m not that smart, i d like too, i cant quiet understand why it is not made so that just works, seems rather basic, it is just signal forwarding :s i suspect go team has its good reasons.

But, for that very common case, we might do something as gross as that,
- if the input command is alike /^go run ..../
- instead of kill(p.PID), lookup into `ps aux` (there should be something similar on windows) for a process in `$TMP/go-build[0-9]+`, get its pid, send it the signals.

Said differently it might be a cross platform kill api, thus the package could use a `Kill(pattern) error` rather than `Kill(pid)error`.

Obviously for some special cases where the user would spawn in // many watched process, or have many `go run` in its process list, things should get buggy.

anyways this is all so weird it just did not work.
