### ISSUE TITLE
New optional parameters: clear and quiet

### ISSUE THREAD

**Issue by jlovas** [loov/watchrun#8]
clear: clear the console at the start of each run
quiet: no output should be written, only the output of the running program

**Comment by egonelbre** [comment]
Instead of `-quiet` I added `-log=silent` (or if you wish to still get errors when the binary doesn't exist etc. `-log=error`).

**Comment by jlovas** [comment]
This will make it even better. Thanks.

**Comment by egonelbre** [comment]
I also added `-clear`

**Comment by jlovas** [comment]
Perfect.
Thank you.
