### ISSUE TITLE
The running go process does not stop if it listens on a server socket.

### ISSUE THREAD

**Issue by jlovas** [loov/watchrun#9]
package main
[...]

func (sh StringHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	io.WriteString(w, sh.message)
}

func main() {
[...]
	err = http.ListenAndServe("localhost:8000", StringHandler{"Hello, World"})
[...]
}

$ watchrun go run main.go

**Comment by egonelbre** [comment]
You need to build and run it in a separate process. `go run` starts the process such that `watchrun` does not have control over it. 

Try using `watchrun "go build -o server . == ./server"`

**Comment by egonelbre** [comment]
I clarified things in README.
